# 配列
1. 複数の要素を持つデータ型
2. 要素は、数値、文字列どちらでもよい
3. 配列のままで変数に格納できる
4. 代表的な配列は、リスト型、numpy型、DataFrame型がある。
5. 配列の要素には、インデックスが付与される

例：

In [1]:
a = [1,2,3,4,5]
print(a)
b = ['今日','の','授業','の','テーマ','は','配列']
print(b)

[1, 2, 3, 4, 5]
['今日', 'の', '授業', 'の', 'テーマ', 'は', '配列']


# 1. リスト型
- 配列のデータ型の中でもっとも基本的な型
- 異なるデータ型を要素に混在できる
  

In [26]:
# 数値を要素とするリスト型
a = [1.0,2.5,5.5]
print(a)
a = [1.0,2.5,5.5+2]
print(a)
# 文字列を要素とするリスト型 - 要素に' '  " "をつけること
b = ['a','f','t']
print(b)
# 型の異なる要素の混在
c = [2,'今日',5,'授業']
print(c)
#変数を要素とする
a = 2
b = '今日'
c = [a,b]
print(c)

[1.0, 2.5, 5.5]
[1.0, 2.5, 7.5]
['a', 'f', 't']
[2, '今日', 5, '授業']
[2, '今日']



### 1) 要素の追加

In [6]:
a.append(2)
print(a)
a.append(6)
print(a)
b.append('h')
print(b)

[1.0, 2.5, 5.5, 2, 6, 2, 6, 2]
[1.0, 2.5, 5.5, 2, 6, 2, 6, 2, 6]
['a', 'f', 't', 'h']


### 2) 繰り返し

In [15]:
a = [0]*10
print(a)
b = [2,6]
c = b*4
print(c)



[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[2, 6, 2, 6, 2, 6, 2, 6]


### 3) 要素の演算

In [25]:
a = sum([1.0, 2.5, 5.5])
print(a)
b = max([1.0, 2.5, 5.5])
print(b)
c = [1.0, 2.5, 5.5]
d=sum(c)/len(c)
print(d)
print('average:',d) #カンマ区切りで複数の要素を表示できる


9.0
5.5
3.0
average: 3.0


### 4) indexによる要素の抽出

In [27]:
a = [1.0, 2.5, 5.5, 2, 6, 2, 6, 2]
print(a[1])
print(a[3:5])
print(a[2:])

2.5
[2, 6]
[5.5, 2, 6, 2, 6, 2]


<img src="attachment:0c743374-7d9b-497c-8c6b-db62af949e04.png" width="60%">

### 5) 文字列への変換  
文字列を要素とするリスト型の場合のみ

In [32]:
a = ['今日','の','天気','は','晴れ']
print(''.join(a))


今日の天気は晴れ


### 6) 2次元配列のリスト
1.リスト型を要素に持つ2重のリスト  
2. 2次元配列と呼ばれる。今まで説明したリスト型は1次元配列
3. 要素のリストを１行とすると、2次元配列は表とみなすことができる
4. indexを使って要素を取り出す場合、2つのindexを指定する必要がある

In [46]:
a = [[1,5,7],[2,3,5],[7,8,4]]
print(a)
print(a[1])
print(a[0][2])
print(a[1][1:])
b = [[1,5,7],[2,5],[8]]
print(b)

c = [['Alice',20,'England'],['Bob',19,'United States'],['Shohei',29,'Japan'],['Mamiko',28,'Japan']]
print(c)

[[1, 5, 7], [2, 3, 5], [7, 8, 4]]
[2, 3, 5]
7
[3, 5]
[[1, 5, 7], [2, 5], [8]]
[['Alice', 20, 'England'], ['Bob', 19, 'United States'], ['Shohei', 29, 'Japan'], ['Mamiko', 28, 'Japan']]


<img src="attachment:22955c86-b0c5-4246-baf3-580bd55f7a2f.png" width="60%">

# 演習1. 
1. Bob Ken Alice Kate を要素とするリストを作成せよ
2. Allen Susan を要素とするリストを作成せよ
3. 上記 1. 2.のリストを連結せよ
4. 上記3.に、Juliaを追加せよ
5. 上記4.から、indexを使ってAliceを取り出せ
6. 同様に、alice kate Allenを取り出せ
7. 上記4.のリストをスペース区切りの文字列　'Bob Ken Alice  に変換せよ(python .join等で検索して答えを見つけてください）

['Bob', 'Ken', 'Alice', 'Kate']
['Bob', 'Ken', 'Alice', 'Kate', 'Allen', 'Susan']
['Bob', 'Ken', 'Alice', 'Kate', 'Allen', 'Susan', 'Julia']
Alice
['Alice', 'Kate', 'Allen']
Bob Ken Alice Kate Allen Susan Julia


# 演習2. 
1. 2 4 6 を要素とするリストを作成せよ
2. 1 3 5 を要素とするリストを作成せよ
3. 上記1. の要素6、および2. の要素3を取り出して、加算した結果を表示せよ（この処理を1行で書くこと）
4. 上記1. 2.を連結して要素の平均を計算せよ


9
3.5


# 演習3.

1. 以下のように1行の要素が、名前 身長 体重 年齢 国籍　であるようなリストを作成し、それを要素とする2次元配列リストを作成せよ  
   Alice 170 60 20 England   Bob 185 75 19 United States  Shohei 192 85 30 Japan  Mamiko 183 75 28 Japan
2. 以下のリストを1.に追加せよ  
   Paul 185 80 31 France
3. 上記2.の2次元配列からindexを使って以下の要素を取り出せ。  
   - Shohei 192 85 30 Japan
   - Maimko
4. 年齢の平均値を求めよ

[['Alice', 170, 60, 20, 'England'], ['Bob', 185, 75, 19, 'United States'], ['Shohei', 192, 85, 30, 'Japan'], ['Mamiko', 183, 75, 28, 'Japan']]
[['Alice', 170, 60, 20, 'England'], ['Bob', 185, 75, 19, 'United States'], ['Shohei', 192, 85, 30, 'Japan'], ['Mamiko', 183, 75, 28, 'Japan'], ['Paul', 185, 80, 31, 'France']]
['Shohei', 192, 85, 30, 'Japan']
Mamiko
25.6


# 2. numpy
1. numerical python 大規模な数値計算を高速に処理するための配列型
2. pythonでの大規模計算は例外なくnumpy型で実行する（ので大変重要）
3. 一見リスト型とよく似ているが、ブロードキャスト（後述）など、numpy独自な高速計算のための様々な仕組みが用意されている

In [55]:
# 数値を要素とするnumpy型
import numpy as np
a = np.array([1.0,2.5,5.5])
print(a)
a = np.array([1.0,2.5,5.5+2])
print(a)
# 文字列を要素とするリスト型 - 要素に' '  " "をつけること
b = np.array(['a','f','t'])
print(b)
# 型の異なる要素の混在
c = np.array([2,'今日',5,'授業'])
print(c)
#変数を要素とする
a = 2
b = '今日'
c = np.array([a,b])
print(c)


[1.  2.5 5.5]
[1.  2.5 7.5]
['a' 'f' 't']
['2' '今日' '5' '授業']
['2' '今日']


### 1) 繰り返し

In [57]:
a = np.zeros(10)
print(a)
b = np.ones(5)
print(b)
c = np.arange(10)
print(c)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[0 1 2 3 4 5 6 7 8 9]


### 2) 要素の演算

In [91]:
a = np.sum([1.0, 2.5, 5.5])
print(a)
b = np.max([1.0, 2.5, 5.5])
print(b)
c = np.mean([1.0, 2.5, 5.5]) #リスト型と異なり、平均を計算する関数がある
print(c)
d = np.prod([1.0, 2.5, 5.5])
print(d)

9.0
5.5
3.0
13.75


<img src="attachment:96aab3f9-1933-42bf-a926-9189f14b0d37.png" width="60%">

**ブロードキャスト**  
numpyの要素に一括でスカラー演算を行うことができる（リスト型ではできない）

In [69]:
a = np.array([1.0, 2.5, 5.5])
print(a)
print(a * 0.5)
print(np.sqrt(a))
print(a**2)
b = np.arange(3)


[1.  2.5 5.5]
[0.5  1.25 2.75]
[1.         1.58113883 2.34520788]
[ 1.    6.25 30.25]
[1.  3.5 7.5]


**対応要素同士の演算（リスト型ではできない）**

In [71]:
a = np.array([1.0, 2.5, 5.5])
b = np.arange(3)
print(a + b)
print(a*b)

[1.  3.5 7.5]
[ 0.   2.5 11. ]


### 3) indexによる要素の取り出し
構文はリスト型と同じ

In [72]:
a = np.array([1.0, 2.5, 5.5, 2, 6, 2, 6, 2])
print(a[1])
print(a[3:5])
print(a[2:])

2.5
[2. 6.]
[5.5 2.  6.  2.  6.  2. ]


### 4) 要素の追加・numpy配列の連結

In [78]:
a = np.array([1.0, 2.5, 5.5, 2, 6, 2, 6, 2])
b = np.append(a,3.5)
print(b)
c = np.array([1.0,3.5,8.2])
d = np.hstack([a,c])
print(d)

[1.  2.5 5.5 2.  6.  2.  6.  2.  3.5]
[1.  2.5 5.5 2.  6.  2.  6.  2.  1.  3.5 8.2]


### 5) 2次元配列のnumpy  
1. numpy型配列を要素に持つ2重のリスト  
2. 2次元配列と呼ばれる。今まで説明したnumpy型は1次元配列
3. 要素のnumpyを１行とすると、2次元配列は表とみなすことができる
4. indexを使って要素を取り出す場合、行と列の2つのindexを指定する必要がある

In [86]:
a = np.array([[1,5,7,9],[2,3,5,7],[7,8,4,2]])
# リスト型と異なり、表のイメージで表示される
print(a)
# 文字列と数値が混在した2次元配列
c = np.array([['Alice',20,'England'],['Bob',19,'United States'],['Shohei',29,'Japan'],['Mamiko',28,'Japan']])
print(c)

[[1 5 7 9]
 [2 3 5 7]
 [7 8 4 2]]
[2 3 5 7]
7
[3 5 7]
[[5 7]
 [3 5]]
[['Alice' '20' 'England']
 ['Bob' '19' 'United States']
 ['Shohei' '29' 'Japan']
 ['Mamiko' '28' 'Japan']]


**スライシング**

In [88]:
print(a[1])
# 要素を取り出す。リスト型と構文が異なる
print(a[0,2])
print(a[1,1:])
print(a[0:2,1:3])


[2 3 5 7]
7
[3 5 7]
[[5 7]
 [3 5]]


<img src="attachment:dd89b1ea-c001-47c3-99ea-f59c9200818e.png" width="60%">

**2次元配列中の配列要素の長さは同一でないとエラーになる（リスト型ではOK)**

In [84]:
b = np.array([[1,5,7],[2,5],[8]])
print(b)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

**2次元配列の連結**  
行方向：axis = 0　列方向 axis = 1

In [116]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = np.array([[1,1,1,1],[2,2,2,2],[3,3,3,3]])
c = np.concatenate([a,b],axis=0)
print(c)
d = np.vstack([a,b])
print(d)
e = np.array([[1,1],[2,2],[3,3]])
f = np.concatenate([a,e],axis=1)
print(f)
g = np.hstack([a,e])
print(g)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]
 [ 2  2  2  2]
 [ 3  3  3  3]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [ 1  1  1  1]
 [ 2  2  2  2]
 [ 3  3  3  3]]
[[ 1  2  3  4  1  1]
 [ 5  6  7  8  2  2]
 [ 9 10 11 12  3  3]]
[[ 1  2  3  4  1  1]
 [ 5  6  7  8  2  2]
 [ 9 10 11 12  3  3]]


<img src="attachment:36417ec2-c805-4aaf-8520-ed475d274fc6.png" width="60%">

**2次元配列の合計**

In [119]:
print(a)
h = np.sum(a, axis=0)
print('行合計',h)
i = np.sum(a,axis=1)
print('列合計',i)
j = np.max(a,axis=0)
print('行最大値',j)
k = np.max(a,axis=1)
print('列最大値',k)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
行合計 [15 18 21 24]
列合計 [10 26 42]
行最大値 [ 9 10 11 12]
列最大値 [ 4  8 12]


<img src="attachment:598198bb-683b-4270-acfd-d45466b846b2.png" width="60%">

**ブロードキャスト**

In [120]:
print(a)
d=a*10
print(d)
e = a * [1,2,3,4]
print(e)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[[ 1  4  9 16]
 [ 5 12 21 32]
 [ 9 20 33 48]]


**条件抽出**

In [163]:
f = a[a>5]
print(f)
g = a[a%2==0]
print(g)

[ 6  7  8  9 10 11]
[ 0  2  4  6  8 10]


**変形**

In [130]:
h = a.reshape(2,6)
print(h)
i = a.reshape(6,2)
print(i)
j = a.reshape(4,3)
print(j)
k = a.reshape(-1,3)
print(k)
l = a.reshape(4,-1)
print(l)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [161]:
w = np.array([1,1,1,1])
x = j + w

ValueError: operands could not be broadcast together with shapes (4,3) (4,) 

In [129]:
w = np.array([1,1,1,1])
v = w.reshape(4,1)
print(v)
x = j + v
print(x)

[[1]
 [1]
 [1]
 [1]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


# 演習1

1. 以下のnumpy配列を作成して5を取り出せ  
  1,3,5,7,9,11,13,15,17,19,21
2. 同様に、9～15を取り出せ
3. 同様に、1~7を取り出せ
4. 上記、2. 3. の対応要素を加算せよ
5. 上記、4.の各要素を二乗せよ
6. 上記、2. 3. 連結して1行8列の表を作成せよ
8. 上記7.の要素の合計を計算せよ

[ 1  3  5  7  9 11 13 15 17 19 21]
5
[ 9 11 13 15]
[1 3 5 7]
[10 14 18 22]
[100 196 324 484]
[ 9 11 13 15  1  3  5  7]
64


# 演習2.

1. 以下のリスト型の配列から2行目の要素5.6を取り出せ  
   c = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
3. 以下の配列をnumpy型に変換して、1.と同じ処理を行え   
4. 変換した配列から、5,6,9,10を行列の形式で取り出せ
5. 配列[[12,13,14,15],[16,17,18,19]]をnumpyにして3.の行方向に連結せよ
6. 配列[20,21,22,23,24]をnumpyにして5.の列方向に連結せよ

[5, 6]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[5 6]
[[ 5  6]
 [ 9 10]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[20]
 [21]
 [22]
 [23]
 [24]]
[[ 0  1  2  3 20]
 [ 4  5  6  7 21]
 [ 8  9 10 11 22]
 [12 13 14 15 23]
 [16 17 18 19 24]]
[[ 0  1  2  3 20]
 [ 4  5  6  7 21]
 [ 8  9 10 11 22]
 [12 13 14 15 23]
 [16 17 18 19 24]]


# 演習3.

1. 以下の1次元配列を3行4列のnumpy 2次元配列に変換せよ  
   0,1,2,3,4,5,6,7,8,9,10,11
2. 上記2次元配列について行合計、列合計を計算せよ
3. 上記の1次元配列を4行3列のnumpy 2次元配列に変換せよ
4. 上記2次元配列について行合計　列合計を計算せよ
5. 同様にして、行毎の平均、列毎の平均を計算せよ
6. 同様にして、行毎の最大値、列毎の最大値を計算せよ

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 6 22 38]
[12 15 18 21]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[ 3 12 21 30]
[18 22 26]
[ 1.  4.  7. 10.]
[4.5 5.5 6.5]
[ 2  5  8 11]
[ 9 10 11]
